# -*- coding: utf-8 -*-
"""NLP_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWcJcZVUGj-JnNFDz6dJLKGbhE8Ky2xV
"""

import pandas as pd
import numpy as np
import shap
import lime.lime_text
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
from google.colab import drive

!pip install lime shap nltk

drive.mount('/content/drive')



# Install and download necessary NLTK data
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Load data from Google Drive
data_path = '/content/drive/MyDrive/Colab Notebooks/synthetic_lung_cancer_cases.csv'
data = pd.read_csv(data_path)

# Combine 'Findings' and 'Impression' into a single text feature
data['text'] = data['Findings'] + ' ' + data['Impression']

# Preprocess target labels
data['Category'] = data['Category'].str.strip()

# Text preprocessing function
def preprocess_text(text):
    """Normalize and preprocess text data."""
    # Lowercase
    text = text.lower()

    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Tokenize and remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatize
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return ' '.join(tokens)

# Apply preprocessing to the text data
data['text'] = data['text'].apply(preprocess_text)

# Split the dataset
X = data['text']
y = data['Category']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Vectorize text using TF-IDF
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

# Train a classifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train_tfidf, y_train)

# Evaluate the model
y_pred = clf.predict(X_test_tfidf)
print(classification_report(y_test, y_pred))

# Save the model and vectorizer to Google Drive
import joblib
model_path = '/content/drive/MyDrive/Colab Notebooks/lung_cancer_classifier_updated.pkl'
vectorizer_path = '/content/drive/MyDrive/Colab Notebooks/tfidf_vectorizer_updated.pkl'
joblib.dump(clf, model_path)
joblib.dump(tfidf, vectorizer_path)

# Function to classify new radiology reports
def classify_report(report):
    """Classify a new radiology report."""
    # Load the saved model and vectorizer
    model = joblib.load('/content/drive/MyDrive/Colab Notebooks/lung_cancer_classifier_updated.pkl')
    vectorizer = joblib.load('/content/drive/MyDrive/Colab Notebooks/tfidf_vectorizer_updated.pkl')

    # Preprocess the input report
    report = preprocess_text(report)

    # Transform the input report
    report_tfidf = vectorizer.transform([report])

    # Predict the category
    prediction = model.predict(report_tfidf)
    return prediction[0]

# Example usage
new_report = "Multiple nodules observed in the upper lobe. Suggestive of malignancy."
print("Predicted Category:", classify_report(new_report))